ekline-io/ekline-github-action

Dockerfile

updating cli version

---

Dockerfile

Merge comment functionality enabled for exact match feedback

---

Dockerfile

updating cli version with analytics

---

entrypoint.sh

updating endtrypoints

---

Dockerfile

updating to latest cli

---

.github/workflows/release.yml

Added latest tag in workflow

---

.github/workflows/release.yml

Add tags to docker image

---

Dockerfile

Update cli version

---

Dockerfile

Update : the cli version

---

entrypoint.sh

update: Bitbucket Integration

---

entrypoint.sh

fix: hardcode for Bitbucket Integration

---

entrypoint.sh

[UPDATE] get the npm run list

---

entrypoint.sh

Updated entrypoint.sh to run ekline on changed files

---

Dockerfile

Update cli to v7.4.2

---

entrypoint.sh

fix: entrypoint.sh to work with empty output.jsonl

---

entrypoint.sh

fix: --ai-suggestion update to entrypoint.sh

---

entrypoint.sh

[FIX] Coment only if there is an output

---

action.yml

fix: added enable_ai_suggestions input

---

Dockerfile

Update: fixed incorrect AI Suggestion

---

Dockerfile

fix: revert to vale 3.4.2

---

Dockerfile

When AI suggestions is enabled we should not show any other non-ai suggesitions
...

 AI suggestions

---

Dockerfile

EK-283-upgraded dockerfile ekline-cli image tag to 7

---

Dockerfile
entrypoint.sh

fix: Enable AI suggestion for PR

---

entrypoint.sh

fix: EkLine job is failing on GitLab

---

entrypoint.sh

fix: gitlab fork repo bug resolved

---

entrypoint.sh

fix: bump the version

---

entrypoint.sh

feat: forked Issue resolved for  GitLab and Bitbucket

---

README.md

Minor update to read me file, it will pull the latest version of the CLI which contains AsciiDoc support

Adding AsciiDoc support

---

.idea/.gitignore
README.md
entrypoint.sh

Adding debug mode for the extension

feat: EK-557 adding debug mode

---

.github/workflows/release.yml

Feat: Implemented trigger of release when ekline-cli is released

---

.github/workflows/release.yml

Updated Release Notes on Dispatch Event

---

Dockerfile
entrypoint.sh
package.json
src/getUserId.ts

Ticket : [Link](https://ekline.atlassian.net/jira/software/projects/EK/boards/1?assignee=712020%3Abf39a77b-882a-43e0-98b9-696d31875731&selectedIssue=EK-555)

feat: Introduced PR Creator and EkLine triggerer

---

entrypoint.sh

Introduced `GitSourceBranchName` and `GitTargetBranchName` for EkLine runs.

feat: Capture the Git branch name for the EkLine review job

---

entrypoint.sh

Bumping the version

---

entrypoint.sh

Ticket Link : [Link](https://ekline.atlassian.net/jira/software/projects/EK/boards/1?assignee=712020%3Abf39a77b-882a-43e0-98b9-696d31875731&selectedIssue=EK-666)
GitLab Test : [Link](https://gitlab.com/djoshi8/gitlabtesting/-/jobs/8726223971)
BitBucket Test : [Link](https://bitbucket.org/ekline-io/test/pipelines/results/192)
GitHub Test : [Link](https://github.com/ekline-io/ekline-github-action-private/actions/runs/12484587026/job/34842185812)

feat: Compute Quality Scores on Non-PR runs

---

README.md
action.yml
entrypoint.sh

feat: review OpenAPI specification files

---

README.md
action.yml
entrypoint.sh

js/EK-675- Add support for excluding directories and files from analysis
